server:
  port: 8761

# service ?? ??? ???? ??
spring:
  application:
    name: discoveryService

# register-with-eureka -> ??? default? true?? ? ??? ??? ??? ???? ???? ??? ?????? false? ??
# fetch-registry
# -> ?? ???? ??? ???? ???? ???? ??? ?? ??? ??? false? ??
# -> Eureka ????? ????? ??? ????? ??? ??? ???? ??, true?? ??? ??? ???? ???.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false